AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  OpenAIAPIKey:
    Description: "OpenAIAPIKey"
    Type: "String"
  RepoName:
    Description: "RepoName"
    Type: "String"
Description: An AWS Serverless Specification template describing your function.
Resources:
  LambdaFunc:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Ref RepoName
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIAPIKey
      MemorySize: 128
      Timeout: 30
      Runtime: python3.10
      CodeUri: .
      Handler: lambda_function.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE
        Cors: 
            AllowCredentials: false
            AllowHeaders: 
              - content-type
            AllowMethods: 
              - POST
            AllowOrigins: 
              - "https://rai-sandeep.github.io"
        InvokeMode: BUFFERED
      Description: ''
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
