AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  REPO_NAME:
    Description: "REPO_NAME"
    Type: "String"
  OPENAI_API_KEY:
    Description: "OPENAI_API_KEY"
    Type: "String"
Description: An AWS Serverless Specification template describing your function.
Resources:
  LambdaFunc:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      FunctionName: !Ref REPO_NAME
      Description: ''
      MemorySize: 128
      Timeout: 30
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      FunctionUrlConfig:
        AuthType: NONE
        Cors: 
            AllowCredentials: false
            AllowHeaders: 
              - content-type
            AllowMethods: 
              - POST
            AllowOrigins: 
              - "*"
        InvokeMode: BUFFERED
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OPENAI_API_KEY
