AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  OpenAIAPIKey:
    Description: "OpenAIAPIKey"
    Type: "String"
Description: An AWS Serverless Specification template describing your function.
Resources:
  BhagavadGitaAI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      FunctionName: bhagava-gita-ai
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::362084602574:role/service-role/BhagavadGita-GPT-role-9ttzunzi
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIAPIKey
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      FunctionUrlConfig:
        AuthType: NONE
        Cors: 
            AllowCredentials: false
            AllowHeaders: 
              - content-type
            AllowMethods: 
              - POST
            AllowOrigins: 
              - "*"
        InvokeMode: BUFFERED
