on:
    push:
      branches:
        - main
jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - uses: aws-actions/setup-sam@v1
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region:  ${{ vars.AWS_REGION }}
        # sam build 
        - run: sam build --use-container
  
  # Run Unit tests- Specify unit tests here 
  
  # sam deploy
        - run: sam deploy --parameter-overrides ParameterKey=OpenAIAPIKey,ParameterValue=${{ secrets.OPENAI_API_KEY }} ParameterKey=RepoName,ParameterValue=${{ github.event.repository.name }} --stack-name ${{ github.event.repository.name }} --capabilities CAPABILITY_IAM --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset